const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

module.exports = {
  mode: 'development',
  devServer: {
    port: 8082
  },
  plugins: [
    // Exposing the files, the remoteEntry.js lists different modules that can be loaded form the Cart project
    new ModuleFederationPlugin({
      name: 'cart', // this name is used in the host when adding this remote
      filename: 'remoteEntry.js', // this is a recommended name
      exposes: {
        './CartShow': './src/bootstrap'  // aliasses filenames => we are exposing the modules ProductsIndex and if
                                          // anyone tries to import product index we are to give them src/index
      },
      shared: ['faker'], // if it was already loaded with a compatible version (the MF plugin validates this against
                        // package.json), it creates a copy of it for this module and does not request it
    }),
    new HtmlWebpackPlugin({
      template: './public/index.html' // it adds automatically the scripts generated by webpack to the HTML
    })
  ]
}