const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

module.exports = {
  mode: 'development',
  devServer: {
    port: 8081
  },
  plugins: [
    // Exposing the files, the remoteEntry.js lists different modules that can be loaded form the Products project
    new ModuleFederationPlugin({
      name: 'products', // this name is used in the host when adding this remote
      filename: 'remoteEntry.js', // this is a recommended name
      exposes: {
        './ProductsIndex': './src/bootstrap'  // aliasses filenames => we are exposing the modules ProductsIndex and if
                                              // anyone tries to import ProductIndex we are giving them src/bootstrap
      },
      shared: ['faker']
    }),
    new HtmlWebpackPlugin({
      template: './public/index.html' // it adds automatically the scripts generated by webpack to the HTML
    })
  ]
}