const HtmlWebpackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');

module.exports = {
  mode: 'development',
  devServer: {
    port: 8080
  },
  plugins: [
    new ModuleFederationPlugin({
      name: 'container',  // not used when we are creating a host module but is added as a convention
      remotes: {
        products: 'products@http://localhost:8081/remoteEntry.js', // the products string before the at has to be identical
                                                                   // to the name in the name of the products MF plugin
        cart: 'cart@http://localhost:8082/remoteEntry.js'
      }
    }),
    new HtmlWebpackPlugin({
      template: './public/index.html' // it adds automatically the scripts generated by webpack to the HTML
    })
  ]
}