const { merge } = require('webpack-merge');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const commonConfig = require('./webpack.common');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');
const packageJson = require('../package.json');

const devConfig = {
  mode: 'development',
  devServer: {
    port: 8081,
    historyApiFallback: {
      index: 'index.html'
    }
  },
  plugins: [
    // Exposing the files, the remoteEntry.js lists different modules that can be loaded form the Markeging project
    new ModuleFederationPlugin({
      name: 'marketing',  // this name is used in the host when adding this remote
      filename: 'remoteEntry.js',  // this is a recommended name
      exposes: {
        './MarketingApp': './src/bootstrap',  // aliasses:files => we are exposing the modules MarketingApp and if
                                              // anyone tries to import MarketingApp we are giving them src/bootstrap
      },
      shared: packageJson.dependencies,
    }),
    new HtmlWebpackPlugin({
      template: './public/index.html' // it adds automatically the scripts generated by webpack to the HTML
    })
  ]
}

module.exports = merge(commonConfig, devConfig);